/**
 * WordPress dependencies
 */
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

/**
 * External dependencies
 */
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');
const path = require('path');

// Extend the default webpack config.
module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry(),
		// frontend theme.
		'frontend/theme': path.resolve(
			process.cwd(),
			'src/frontend/js/theme.js'
		),
		// admin settings tabs.
		'admin/settings-tabs': path.resolve(
			process.cwd(),
			'src/admin/js/settings-tabs.js'
		),

		// block editor styles.
		'editor/block-editor': path.resolve(
			process.cwd(),
			'src/editor/blocks.scss'
		),
	},

	plugins: [
		// Include WP's plugin config.
		...defaultConfig.plugins,

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin({
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		}),
	],
};